version: '3.1'
services:
    app:
        build: ./HealthStack
        command: python -u app.py
        ports:
            - 5000:5000
        links:
            - db
        depends_on:
            - db
        container_name: healthDB
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: healthyboi
            MYSQL_DATABASE: healthDB
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        restart: always
        ports:
            - 1234:1234
        container_name: healthDBContainer
    mongodb:
        image: mongodb/mongodb-community-server:6.0-ubi8
        environment:
            - MONGODB_INITDB_ROOT_USERNAME=user
            - MONGODB_INITDB_ROOT_PASSWORD=pass
        volumes:
            - type: bind
              source: ./data
              target: /data/db
    mongodbconnection:
        image: mongodb/mongodb-community-server:6.0-ubi8
        environment:
          - CONN_STR=mongodb://user:pass@mongodb
          - MONGO_URL=mongodb://mongod:27017/dbname
        command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
        links:
            - mongodb
        depends_on:
          - mongodb